title: Github with Jekyll
author: Sarah Bartley
email: sbartley1080@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm modifying the config file in Github. These are some of the changes that I've made to the file. Particularly the theme.
theme: minima

# social links
twitter_username: TheOriginalBPC
github_username:  BritishPandaChick

show_excerpts: true # set to false to remove excerpts on the homepage
